
server:
  port: 8086

spring:
  datasource:
    url: jdbc:h2:file:C:/h2data/sample
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
    
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        
    show-sql: true    
    database-platform: org.hibernate.dialect.H2Dialect
    
  h2:
    console:
      enabled: true
  application:
    name: customer-service
  
  
         
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
